### ISSUE TITLE
1.29 - CSI Spec Change

### ISSUE THREAD

**Issue by sunnylovestiramisu** [kubernetes-csi/kubernetes-csi.github.io#11]
https://github.com/container-storage-interface/spec/pull/544 needs to get approved and merged.

**Comment by carlory** [comment]
Hi @sunnylovestiramisu 

container-storage-interface/spec#544 is merged, this issue should be closed.

**Comment by sunnylovestiramisu** [comment]
Just back from vacation :)

/close
